import pandas as pd
import plotly.graph_objects as go
import sys

# 1. Load the CSV generated by Go
csv_file = "MonteCarloSim.csv"
try:
    df = pd.read_csv(csv_file)
except FileNotFoundError:
    print(f"Error: Could not find {csv_file}. Run 'go run main.go' first!")
    sys.exit(1)

print(f"Detected CSV Columns: {list(df.columns)}")

# 2. Grab the 3 columns by position (X = Strike, Y = Expiration, Z = Option Price)
col_x = df.columns[0]
col_y = df.columns[1]
col_z = df.columns[2]

# 3. Extract unique values for the 3D grid axes
X = df[col_x].unique()
Y = df[col_y].unique()

# 4. Pivot the flat 3D list into a 2D matrix for Plotly's Z-heights
Z = df.pivot(index=col_x, columns=col_y, values=col_z).values

# 5. Build the Interactive 3D Surface Object
fig = go.Figure(data=[go.Surface(
    x=X,
    y=Y,
    z=Z,
    colorscale="Inferno",  # Heatmap color scale based on Option Price height
    colorbar=dict(title="Option Price ($)"),
    hovertemplate=(
        "Strike (X): $%{x:.2f}<br>" +
        "Expiration (Y): %{y} days<br>" +
        "Option Price (Z): $%{z:.2f}<extra></extra>"
    )
)])

# 6. Set 3D Camera and Axis Labels
fig.update_layout(
    title="Interactive 3D Monte Carlo Option Price Surface",
    scene=dict(
        xaxis_title="Strike Price ($)",
        yaxis_title="Expiration (Days)",
        zaxis_title="Option Price ($)",
        aspectmode="manual",
        aspectratio=dict(x=1, y=1, z=0.8), # Increase 'z' (e.g., 0.8 to 1.2) for a steeper curve
        camera=dict(
            eye=dict(x=1.6, y=1.6, z=1.2)  # Initial 3D viewing perspective
        )
    ),
    autosize=True,
    margin=dict(l=65, r=50, b=65, t=90)
)

# 7. Pop open the 3D surface in your default browser!
fig.show()